### ISSUE TITLE
The `lfortran.exe` executable fails to run on Windows

### ISSUE THREAD

**Issue by certik** [conda-forge/lfortran-feedstock#17]
The error one gets is:

![Screenshot from 2020-10-07 13-58-19](https://user-images.githubusercontent.com/20568/95390640-f4407d00-08b2-11eb-99cb-741d2cf4a257.png)

```
lfortran.exe - Entry Point Not Found
The procedure entry point could not be located in the dynamic link library c:\...\lfortran.exe
```

**Comment by certik** [comment]
By searching this error online, it seems it is caused by some of the dlls to be missing.

https://errortools.com/windows/fixing-the-procedure-entry-point-could-not-be-located-in-the-dynamic-link-library-error-in-windows-10/

The sites usually suggest to run `sfc /scannow`, which finishes without any errors and does not fix the problem.

**Comment by certik** [comment]
The other issue is that we actually ask conda to test the executable on Windows:

https://github.com/conda-forge/lfortran-feedstock/blob/10fbedd5ca9e8a2be50a41d8a06e1b66d3f68d91/recipe/meta.yaml#L34

But that line does not seem to actually be executed:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=211496&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=1906

The last line is:
```
(%PREFIX%) %SRC_DIR%>if exist %PREFIX%\Library\bin\lfortran.exe (exit 0 )  else (exit 1 ) 
```
That seems like a bug in `conda-build`.

**Comment by isuruf** [comment]
@conda-forge/xeus, looks like xeus breaks ABI compatibility in patch versions on windows. Is this a known bug?

**Comment by certik** [comment]
The issue was that the XEUS package had some missing symbols, more details in #18. The updated `lfortran` package is now being built by conda-forge and that should fix it.

**Comment by JohanMabille** [comment]
> @conda-forge/xeus, looks like xeus breaks ABI compatibility in patch versions on windows. Is this a known bug?

No, we need to check what we did wrong.
