### ISSUE TITLE
arm64: Run lfortran to pre-compile the runtime library

### ISSUE THREAD

**Issue by certik** [conda-forge/lfortran-feedstock#29]
In #26 and #28 we disabled the compilation of the runtime library in LFortran because the arm64 package is cross-compiled, so one cannot run the lfortran binary after building it.

We have to figure out how to compile LFortran on the host system, and use that to pre-compile the runtime library. Then use the cross-compiled version to install in the conda package.

**Comment by certik** [comment]
@isuruf do you know by any chance how to do this?

**Comment by isuruf** [comment]
Can `lfortran` itself cross compile?

**Comment by certik** [comment]
Not yet, although that would probably be quite easy to implement.

However, the pre-compiled runtime library is not actually compiled to machine code (yet), right now we compile each module to a Fortran mod file, which is just a binary representation of LFortran's ASR. The ASR is platform independent, so it can be generated from any platform. All we need is to somehow run lfortran at the build machine.

**Comment by isuruf** [comment]
Ah, then you can just add,
```
requirements:
   build:
     - lfortran  # [build_platform != target_platform]
```
and then add an option to CMake to use an already built lfortran.

**Comment by isuruf** [comment]
This has the disadvantage that you the first time you build a new lfortran version, arm64 package will fail and then you'll have to restart it after x86_64 is merged.

The other option is to build a x86_64 lfortran in the arm64 build. That's possible too.

**Comment by certik** [comment]
I think https://github.com/conda-forge/lfortran-feedstock/pull/30 will fix it.

**Comment by certik** [comment]
This has been fixed for some time using the double compilation approach.
