### ISSUE TITLE
antlr-python-runtime 4.8

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/lfortran-feedstock#5]
Just dug this feedstock up from a [search](https://github.com/search?q=org%3Aconda-forge+antlr-python-runtime&type=Code), but heads up that `antlr-python-runtime 4.8` is [ready to drop](https://github.com/conda-forge/antlr-python-runtime-feedstock/pull/4) and very possibly could break this package if the upstream is including code compiled from grammars with the `4.7` line. Please reply on that PR if you need me to wait to release it!

**Comment by certik** [comment]
Go ahead and release it. I'll fix it up upstream and update the Conda package afterwards.

**Comment by certik** [comment]
We have removed the dependency on ANTLR, so the PR #10 will close this issue once it works.
