### ISSUE TITLE
Undefined symbol `__availability_version_check` with LLVM 17 on macOS Intel (osx-64)

### ISSUE THREAD

**Issue by certik** [conda-forge/lfortran-feedstock#96]
We are getting the following linker error with Clang 17 (LLVM 17) on osx intel:
```
[ 93%] Linking CXX executable test_lfortran
Undefined symbols for architecture x86_64:
  "__availability_version_check", referenced from:
      ___isPlatformVersionAtLeast in libclang_rt.osx.a(os_version_check.c.o)
      __initializeAvailabilityCheck in libclang_rt.osx.a(os_version_check.c.o)
ld: symbol(s) not found for architecture x86_64
x86_64-apple-darwin13.4: error: linker command failed with exit code 1 (use -v to see invocation)
```

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1009656&view=logs&j=a3733481-72bd-515a-076a-bb2a92643e95&t=e8fb3a0d-1847-59c9-62a5-d55cea7e690a

See also https://github.com/conda-forge/lfortran-feedstock/pull/94#issuecomment-2308532774, the PR that triggered it.

This error does not happen on macOS/arm.

The only workaround that we know about so far is to use Clang 16 / LLVM 16 for macOS/intel.

**Comment by h-vetinari** [comment]
I opened an issue for this: https://github.com/conda-forge/clang-compiler-activation-feedstock/issues/139

**Comment by certik** [comment]
Thanks @h-vetinari ! If you figure out how to fix it, that would be a huge help.

**Comment by h-vetinari** [comment]
Can you try again? Should be fixed now...

**Comment by h-vetinari** [comment]
Closing this as obsolete
